const TITLE_PLAY = "PLAY";
const TITLE_PAUSE = "PAUSE";
const TITLE_RANKING = "RANKING";
const TITLE_SETTING = "SETTING";
const TITLE_REGISTER = "REGISTER";
const TITLE_POLYOMINO = "POLYOMINO";

export {
  TITLE_PLAY,
  TITLE_PAUSE,
  TITLE_RANKING,
  TITLE_SETTING,
  TITLE_REGISTER,
  TITLE_POLYOMINO,
};
