const TITLE_PLAY = "PLAY";
const TITLE_RANKING = "RANKING";
const TITLE_SETTING = "SETTING";
const TITLE_REGISTER = "REGISTER";

export {
  TITLE_PLAY,
  TITLE_RANKING,
  TITLE_SETTING,
  TITLE_REGISTER,
};
